### ISSUE TITLE
Two-way exits

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#31]
Since two-way exits are the norm, it would perhaps be easier if by default, a two way exit were created initially.  It would save some work!

**Comment by Gwyrdain** [comment]
Added.  So long as an additional room vnum is available, a new "empty room," and reciprocal exit (both sides) will be created.

**Comment by Cordir** [comment]
![image](https://cloud.githubusercontent.com/assets/10890489/6316697/4e0fb618-b9f7-11e4-9ba7-c8f23ad4c9aa.png)


Unintended ooops -- I built all the rooms FIRST, then began linking them, and when I clicked East to create an exit to the EAST, I got the above message.

**Comment by Cordir** [comment]
(ie, I cannot now create any exit links at all.)

**Comment by Cordir** [comment]
I think maybe there needs to be two options for exits:
button/link 1) You just create a reciprocal exit between existing rooms.
button/link 2) You create-as-you-go with rooms created dynamically.

Maybe having it be a choice in area creation would be better, so that it turns on one option or the other, to accommodate both writing styles?

**Comment by Gwyrdain** [comment]
Right now, to add an exit without adding a new room, you would use the button in the exits list...
![image](https://cloud.githubusercontent.com/assets/7820937/6316928/fc739f10-b9f4-11e4-80d0-9c8f9695bdc4.png)
I understand and agree with what you're getting at.  Need to open as a new issue/feature though.
