### ISSUE TITLE
Add warnings for ldesc length contextually (with prefixes)?

### ISSUE THREAD

**Issue by Gwyrdain** [Gwyrdain/apprentices-workshop#43]
E.g., the below ldesc's are nominally ok, but "too long" when the prefixes are displayed.

![image](https://cloud.githubusercontent.com/assets/7820937/6322110/2cb19232-bacb-11e4-8983-d41988ed7cec.png)

**Comment by Cordir** [comment]
Oh, hey, look at those rulers being helpful! :D

**Comment by Gwyrdain** [comment]
Added to area review.

**Comment by TokugawaTFC** [comment]
Were the mob prefixes removed from the Review check and mob record? There are a few mobs in the Boneyard in which the long descriptions are too long due to the prefixes. It would be helpful to have the Review section call this out. As it is I don't think it considers the prefixes currently.

Below is an example.
Mob 32742 is 85 characters long with the prefixes.
(Light Red Aura) (White Aura) Smiling wickedly, Elizabeth gazes at you appraisingly.

**Comment by Gwyrdain** [comment]
See Issue #100.  I had incorrectly included the word "Light " in this calculation.
