### ISSUE TITLE
The Illogic of it

### ISSUE THREAD

**Issue by tyn-** [Gwyrdain/apprentices-workshop#55]
When an illogical exit is created (e.g. south from one room goes into east of another), one side is properly shown as an illogical exit, but the other is shown as a one-way.  The review also sees things this way.

**Comment by Gwyrdain** [comment]
It works as I _had_ intended... since each exit stands on it's own (i.e., is discretely defined) each exit looks at things from it's own perspective...  if there's no reverse path on the far side I am one-way... if there's a reverse path on the far side that goes somewhere else I am illogical (i.e., one expects to go north south and end up the same place).

What you're talking about is more from a room perspective... if there's any way back I'm not one-way, etc.  I understand and that makes sense too.  I think I'll categorize this secondary priority though since it's kindof a matter semantics and since at least the warnings are still generated at present.

**Comment by Gwyrdain** [comment]
new logic in place.
