### ISSUE TITLE
Update UI & output to allow multiple mobile special functions

### ISSUE THREAD

**Issue by Gwyrdain** [Gwyrdain/apprentices-workshop#60]

**Comment by tyn-** [comment]
HAHA, when I read this on my phone, I thought you were saying it had been done!  And I was, like, WOO HOO!, because I was getting ready to edit the rest of the area by hand, including the multiple spec funs, and it looked like that part was ready.  DOH!

In all seriousness, this editor is pretty sweet.  Thanks for your work on it.

**Comment by Gwyrdain** [comment]
Yes, that was just a reminder to finish.  Done now.
