### ISSUE TITLE
Directional Descriptions

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#70]
When you create a directional description... it looks like this:
![directional descriptions](https://cloud.githubusercontent.com/assets/10890489/7573977/713edbec-f7ef-11e4-9307-07a492b6bf5c.JPG)

* The "Reciprocal" option should be removed.
* The Keyword field should be removed: If it's a directional description, it should be linked to the exit description. If there's additional keywords, that would stray into the realm of Extra descriptions.
* Having more room (ie, a (rulered) text block as you do for a room description) would be Very Helpful. As is, it's a single line field  you can type into, but not see the entirety of what you've entered.

**Comment by Cordir** [comment]
Also, if you try to hit enter to have another paragraph in the existing Description, it boots you out of the record you are working on.

**Comment by Cordir** [comment]
Also, if you compose the text in notepad, with formatting (such as spaces between paragraphs), it deletes them, and you get your text all mashed up into a single paragraph.  :(

**Comment by Gwyrdain** [comment]
1.  Reciprocal:  Agree to fix as a bug.
2.  Keyword: You mean removed when an exit is look only?  Even so, IMO, this is an editorial comment rather than technical.  Another author may want both "look north" and "look window" to render the same text as you gaze north out the window at the snow covered peaks.
3.  Description:  Added ruler and made paragraph style.

**Comment by Gwyrdain** [comment]
Reciprocality was in some cases inappropriately displaying for look-only exits.  This should be fixed.
