### ISSUE TITLE
Mob Extended Functions

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#75]
Per Tynian, mobs CAN have more than one extended function, but the Apprentice's Workshop will only allow me to give them one. Can I have moar? :D 

(See: https://forum.tfcmud.com/showthread.php/3784-Act_On_Give )

**Comment by Gwyrdain** [comment]
AW doesn't preclude multiple per se, but precludes more than one of the same.  Normal spec functions should not be used multiple times.  Whether extended should be allowed multiple times probably depends on which?  E.g., probably spec_call_for_help should not be used more than once per mobile.  Spec_mage_protector only once?  Spec_timed_teleport allow multi?  Spec_act_on_give is understood as yes.

**Comment by tyn-** [comment]
In skimming the function list, I didn't see other special functions you
would use more than once on a mob...

Would you concur, Cordir?
On Apr 7, 2016 9:15 PM, "Gwyrdain" <notifications@github.com> wrote:

AW doesn't preclude multiple per se, but precludes more than one of the
same. Normal spec functions should not be used multiple times. Whether
extended should be allowed multiple times probably depends on which? E.g.,
probably spec_call_for_help should not be used more than once per mobile.
Spec_mage_protector only once? Spec_timed_teleport allow multi?
Spec_act_on_give is understood as yes.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/Gwyrdain/apprentices-workshop/issues/75#issuecomment-207202318>

**Comment by Cordir** [comment]
Concur, act_on_give is the one you'd want to use more than once. :)

**Comment by Gwyrdain** [comment]
Duplicate spec_act_on_give (only) is now permitted.
