### ISSUE TITLE
Ability to Rotate zone?

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#79]
One functionality that Sirak's Muditor has that I've never needed to use - until now - is the ability to rotate a zone, so that it fits the area that it will be linked to. Would it be possible to have that functionality, to choose to rotate 90, 180, 270 degrees, and have the exits updated automagically?

**Comment by Gwyrdain** [comment]
```
modulus divide ( direction value + x / 4 )
where x for 90° = -1
where x for 180° = -2
where x for 270° = -3
```

**Comment by Gwyrdain** [comment]
Because of the way the randomize reset works, it's not possible to rotate it.  Say it were randomize north, and you rotate 90°.  There is no randomize west available.

![image](https://cloud.githubusercontent.com/assets/7820937/14590208/29b09fea-04aa-11e6-8715-fdf92fc91c99.png)

What behavior is preferred?

1. Reset remains as is (and is potentially wrong).
2. Delete all randomize resets.
3. Delete randomize resets 0, 1, and 2 (n, n+s, n+s+e) and leave 3, 4, and 5 (upon which rotate has no effect.

**Comment by Cordir** [comment]
My vote is  1. The area writer should get a prompt saying they should examine their randomized exits after rotation.

**Comment by Gwyrdain** [comment]
This is now available on the area page:

![image](https://cloud.githubusercontent.com/assets/7820937/14591041/4403c4a8-04be-11e6-9882-919376be57d6.png)

Try it on the shared sample area 'The Practice Fields'.
