### ISSUE TITLE
Display Vnums in Resets

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#83]
When you are on the Resets page, it displays the names but not the vnums of items, rooms, and mobs. As sometimes things have the same name, it would be helpful to also display the Vnum of the room, mob, or object.

**Comment by Gwyrdain** [comment]
I added a vnum column to the main table for the primary vnum... however, I'm not sure that that's what you really want?  Please advise -- i.e., how would you layout the page for usability?

**Comment by Cordir** [comment]
That absolutely helps.  Perhaps this addition:

MOBILE	39055	Load 'a scraeling' at 'Within an Ephemeral Web' (Room 39041)
and 
MOBILE	39002	Load 'Megan, an assistant librarian' at 'The Grand Library Arcana Room'
Dependent Resets
Equip 'Megan, an assistant librarian' with 'a brass key on a long neckchain' (Object 39068) as 1ST NECK

**Comment by Gwyrdain** [comment]
Since you are talking about inline vnums I though it would be more symmetrical to just show both the primary and target vnums inline.  I did omit the prefix "room/mobile/object" and just showed the vnum in parenthesis.  Review and advise.  I still don't love this table, but... maybe it can be revisited later.

**Comment by Cordir** [comment]
This is a big help, and it meets my needs on this issue :)
