### ISSUE TITLE
Directional descriptions displayed as Exits

### ISSUE THREAD

**Issue by Cordir** [Gwyrdain/apprentices-workshop#85]
This room ONLY has an exit to the east, but because it has directional descriptions in place for the other directions, they are displaying as exits in the Formatted Block:

![image](https://cloud.githubusercontent.com/assets/10890489/14679936/92834cd2-06e1-11e6-9965-a33540e15332.png)

This causes some confusion when double checking one's map.  Perhaps Directions with Discriptions but not exits could be displayed differently? 

The Grand Library Cartography Room
[Exits: east]
[Descriptions: north east south west down]

**Comment by tyn-** [comment]
... Or enclosing the faux exits in parentheses, if you want to keep exits
to one line.
On Apr 20, 2016 8:22 AM, "Cordir" <notifications@github.com> wrote:

This room ONLY has an exit to the east, but because it has directional
descriptions in place for the other directions, they are displaying as
exits in the Formatted Block:

[image: image]
<https://cloud.githubusercontent.com/assets/10890489/14679936/92834cd2-06e1-11e6-9965-a33540e15332.png>

This causes some confusion when double checking one's map. Perhaps
Directions with Discriptions but not exits could be displayed differently?

The Grand Library Cartography Room
[Exits: east]
[Descriptions: north east south west down]

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/Gwyrdain/apprentices-workshop/issues/85>

**Comment by Gwyrdain** [comment]
Separated and grayed similar to resets.

**Comment by Gwyrdain** [comment]
corrected a problem with </u> close tag.  Looks like this:
![image](https://cloud.githubusercontent.com/assets/7820937/14694768/8d900a1e-0720-11e6-97fb-7232525996a9.png)

Closing issue, advise if issues arise.  At some point I will want to see the actual look descriptions appear on this page rather than have these look directions be edit links (in the same vein as the in room mobiles).
